### ISSUE TITLE
All svd files seem invalid

### ISSUE THREAD

**Issue by D4N** [bnahill/PyCortexMDebug#14]
I tried your project but I have had some troubles with the svd_load function which seems to reject all svd files that I found.
To be more precise, I cloned your repository, start gdb in the repos root folder and run:
```
(gdb) source cmdebug/svd_gdb.py
(gdb) svd_load ../cmsis-svd/data/TexasInstruments/TM4C1230H6PM.svd
Loading SVD file ../cmsis-svd/data/TexasInstruments/TM4C1230H6PM.svd...
Error loading file ../cmsis-svd/data/TexasInstruments/TM4C1230H6PM.svd
```
The folder ../cmsis-svd/ is the git repository https://github.com/posborne/cmsis-svd. I have tried various files from there, but all of them result in the same outcome. I have also tried this with my stock gdb:
```
$ gdb --version
GNU gdb (GDB) Fedora 7.12.1-48.fc25
```
and arm-none-eabi-gdb-py from ARM:
```
$ arm-none-eabi-gdb-py --version
GNU gdb (GNU Tools for ARM Embedded Processors 6-2017-q1-update) 7.12.1.20170215-git
```
Both produce the same outcome.

Thank you in advance,
Dan

**Comment by bnahill** [comment]
This should all be fixed now. When I wrote this, virtually no vendors actually provided SVD files. Some have a bit of a different style now. Comments broke the parser on some files. Others got broken by variations in how bit ranges are specified for fields within a register. Try it out and let me know how it goes. I didn't test with GDB, but a handful of files from TI, Nordic, SiLabs, Toshiba, NXP, and ST all seemed to parse correctly without exploding.

**Comment by D4N** [comment]
Thanks a lot for the fix, I have tried some svd files and they can be loaded in gdb. Once I have the svd file for my CPU, I can give this a more thorough try, but for now this issue should be fixed.
