### ISSUE TITLE
SVD accessType is not respected

### ISSUE THREAD

**Issue by hazelnusse** [bnahill/PyCortexMDebug#15]
CMSIS SVD schema defines an access field of type `accessType`:
https://arm-software.github.io/CMSIS_5/SVD/html/schema_1_2_gr.html

Valid values are `read-only`, `write-only`, `read-write`, `writeOnce`, and `read-writeOnce`.

When a peripheral register has `access == write-only`, printing that register causes a bus fault. In my case, the TDR register in the LPSPI peripherals on the NXP S32K part are write-only. Printing the state of the LPSPI0 triggers a bus fault when attempting to do something like `svd LPSPI0`.

**Comment by bnahill** [comment]
Thanks for reporting this! Check the above commit and let me know if it works for you. I tested the parser, but not the GDB side of things yet... It _should_ avoid reads to write-only registers and writes to read-only registers.

**Comment by hazelnusse** [comment]
I'll test in the morning -- thanks for the quick response!
