### ISSUE TITLE
svd_load by vendor + model

### ISSUE THREAD

**Issue by fenugrec** [bnahill/PyCortexMDebug#21]
svd_load does file completion which is cool, but it would be even nicer if it could take input of the form
`svd_load <vendor> <device>`
such as 
`svd_load STMicro STM32F103xx.svd`

It seems it's been done, not sure if you'd be able to port the relevant code :
https://gist.github.com/devanlai/644910b712361e7317ec2305884aea8d

**Comment by bnahill** [comment]
Sorry for the huge delay on this. At first glance it didn't make much sense and it just sat in my inbox, but it's now clear, and yes that would be pretty cool. Should also be pretty easy. Time is really tight these days but I'll look into it! Cool idea!

**Comment by bnahill** [comment]
18 months later: The PR from @grevaillot (https://github.com/bnahill/PyCortexMDebug/pull/23) should cover this. Please re-open if not.
