### ISSUE TITLE
Unexpected Negative Values

### ISSUE THREAD

**Issue by zaber-paul** [bnahill/PyCortexMDebug#24]
Using STM32H743x.svd from STMicro, many of the registers/fields read out as negative values, which I was not expecting (seems to affect a few registers in every peripheral, I haven't found a specific pattern).

Example (registers in `Flash`):

```
svd/x Flash
...
        OPTCCR:      (not readable)  FLASH option clear control register
        PRAR_CUR1:       0x000000FF  FLASH protection address for bank 1
        PRAR_PRG1:       0x000000FF  FLASH protection address for bank 1
        SCAR_CUR1:      0x-7FFFFF01  FLASH secure address for bank 1
        SCAR_PRG1:      0x-7FFFFF01  FLASH secure address for bank 1 
...
```

Fields in example register which reads negative (`Flash`, `SCAR_CUR` from above):
```
svd/x Flash SCAR_CUR1
Fields in Flash SCAR_CUR1:
        SEC_AREA_START1:  0x0FF  Bank 1 lowest secure protected address
        SEC_AREA_END1:    0x000  Bank 1 highest secure protected address
        DMES1:              0x1  Bank 1 secure protected erase enable option status bit
```

**Comment by bnahill** [comment]
Hmmm, it looks like these are read as signed values by default. The struct format strings come from the BITS_TO_UNPACK_FORMAT dict which specifies "b", "h", and "i" (all signed). They should probably be "B", "H", "I". It was a while ago, but I'd like to think there was a reason for that now-unfortunate choice. Can you see any reason those should be signed by default? I don't recall if SVD allows for indicating that a field is signed.

Could you try out that change? I'm expecting that your current problem occurs only when the MSb is a 1, indicating a negative value when parsed as twos-complement.

**Comment by zaber-paul** [comment]
I agree with your expectation that the negative numbers only arise when MBb is set.

I tried changing the `BITS_TO_UNPACK_FORMAT` to uppercase (unsigned) and the output matches reading from register directly via GDB `x <addr>`. It was quite incorrect when parsed as 2's complement. Looks like that would at least fix the issues I've been seeing!

**Comment by zaber-paul** [comment]
4a69407 appears to have resolved this issue for me, feel free to close as successfully resolved!

**Comment by bnahill** [comment]
Thanks for testing!
