### ISSUE TITLE
LPC176x5x_v0.2.svd fails to load

### ISSUE THREAD

**Issue by Palmitoxico** [bnahill/PyCortexMDebug#36]
Commit 98fd8c1d60a289892d6f3e1d7969a56f12ac4e24 introduced a regression and I'm no longer able to parse the [LPC17x5x_v0.2.svd](https://github.com/bnahill/PyCortexMDebug/files/5983729/LPC176x5x_v0.2.zip) file.

Upon locading It prints:
```
Could not load SVD file ../scripts/gdb/LPC176x5x_v0.2.svd : no such child: value...
```

This commit introduce major changes, I'll investigate it further to identify where exactly the bug is.

**Comment by bnahill** [comment]
I'm surprised this wasn't broken before. It looks like it gets mad that there's an enumeratedValue that doesn't have a value:

 LPC17x5x_v0.2.svd:199
```
                                                                <enumeratedValue>
                                                                        <name>RESERVED</name>
                                                                        <description>Reserved.</description>
                                                                        <isDefault>true</isDefault>
                                                                        
                                                                </enumeratedValue>
```

I'm not sure what NXP meant by this, but I committed a simple fix. I didn't realize it would close the issue. Feel free to re-open if this doesn't solve your problem.
Thanks!

**Comment by Palmitoxico** [comment]
Working perfectly now. Thanks!
